name: Publish binary
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up 64 tass on Ubuntu
        run: |
          sudo apt-get install 64tass
      - name: Build Binary
        run: |
          make
          make pgz
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cartridge image
          path: |
            loader.bin
            selector.pgz
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            loader.bin
            selector.pgz
          tag_name: ${{ github.ref_name }}
          body: "Automated release of ${{ github.ref_name }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          